config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :worlds
  resources :brainstorm, only: [:index]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :world
  validates :title, :pov, :synopsis, :description, :location, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :worlds

  validates :username, :email, presence: true
  validates :username, length: { minimum: 3}
  validates :username, :email, uniqueness: true
  validates :password, length: { in: 6..20 }
  validates :password, presence: true, allow_nil: true, confirmation: true
  validates_confirmation_of :password

end

app/models/world.rb
class World < ApplicationRecord
  belongs_to :user
  has_many :chapters
  validates :title, :description, :genre, :inspiration, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/brainstorm_controller.rb
class BrainstormController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if logged_in?
      redirect_to user_path(@current_user)
    else
      @user = User.new
    end
  end

  def create
   @user = User.find_by(username: params[:user][:username])
      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        flash[:message] = 'Failed to log in'
        redirect_to '/login'
     end
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:message] = "#{@user.username} created successfully!"
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_info_params)
      flash[:message] = "#{@user.username} updated successfully!"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def user_info_params
    params.require(:user).permit(:username, :password, :bio, :favorite_genre)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
  def index
    @worlds = World.all
  end

  def new
    @world = World.new
  end

  def create
    @world = World.new(world_params)
    if @world.save
      redirect_to world_path(@world)
    else
      render :new
    end
  end

  private

  def world_params
    params.require(:world).permit(:title, :description, :genre, :inspiration)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def errors_for(model, attribute)
    if model.errors[attribute].present?
      content_tag :span, :class => 'error_explanation' do
      model.errors[attribute].join(", ")
      end
    end
  end

  def avatar_url(user)
      gravatar_id = Digest::MD5::hexdigest(user.username).downcase
      "http://gravatar.com/avatar/#{gravatar_id}.png?s=64"
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/worlds_helper.rb
module WorldsHelper
end

app/views/brainstorm/index.html.erb
<div class="brainstorm">
  <h1>Welcome to Brainstorming</h1>
  <p>Writers can share their worldbuilding ideas and collaborate with others to bring their world to life.</p>
</div>

app/views/home/index.html.erb
<div class="home">
  <h1>Worldbuilding</h1>
  <%= image_tag("middle-earth.jpg", width: "672", height: "420") %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Worldbuilding App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Source+Sans+Pro|Roboto:700', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="flash-message">
      <% if flash[:message] %>
        <h3><%= flash[:message] %></h3>
      <% end %>
    </div>

    <header>
    <nav class="navigation" id="navMenu">
      <a href="javascript:void(0);" class="icon" onclick="responsiveMenu()">
        <i class="fa fa-bars" style="font-size:24px"></i>
      </a>
      <%= link_to "Worldbuilding", root_path %>
      <%= link_to "Create World", worlds_path %>
      <% if !logged_in? %>
        <%= link_to "Sign Up", new_user_path %>
        <%= link_to "Login", '/login' %>
      <% elsif logged_in? %>
      <%= link_to "Writers", users_path %>
      <%= link_to "Brainstorm", brainstorm_index_path %>
      <%= link_to "Profile", user_path(current_user) %>
      <%= link_to "Logout", '/logout' %>
      <% end %>
    </nav>
  </header>

    <script>
        function responsiveMenu() {
          let x = document.getElementById("navMenu");
          if (x.className === "navigation") {
            x.className += " responsive";
          } else {
            x.className = "navigation";
          }
        }
    </script>
    <%= yield %>
  </body>
</html>

app/views/series/index.html.erb
<div class="series-content">
  <h1>Create Series</h1>
  <h2>Characters</h2>
  <h2>Culture</h2>
  <h2>Geography</h2>
  <h2>History</h2>
  <h2>Narrative</h2>
</div>

app/views/users/edit.html.erb
<div class="edit-user">
  <% if current_user %>
  <h2>Edit Profile</h2>
  <%= form_for @user do |f| %>
    <%= f.label :username, "Username", class: 'form-label' %>
    <%= f.text_field :username, class: 'form-text-box' %>

    <%= f.label :password, "Password", class: 'form-label' %>
    <%= f.password_field :password, class: 'form-text-box' %>

    <%= f.label :bio, "Bio", class: 'form-label' %>
    <%= f.text_area :bio, class: 'form-text-area' %>

    <%= f.label :favorite_genre, "Favorite Genre", class: 'form-label' %>
    <%= f.text_field :favorite_genre, class: 'form-text-box' %>

    <%= f.submit "Update Profile", :class => 'form-submit-box' %>
  <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="users-index">
  <h1>Writers Corner</h1>

  <% @users.each do |user| %>
    <h2><%= user.username %></h2>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="sign-up">
<h1>Sign Up</h1>
<%= form_for @user do |f| %>

  <%= f.label :username, "Username", class: 'form-label' %>
  <%= f.text_field :username, class: 'form-text-box' %>
  <%= errors_for @user, :username %>

  <%= f.label :email, "Email", class: 'form-label' %>
  <%= f.text_field :email, class: 'form-text-box' %>
  <%= errors_for @user, :email %>

  <%= f.label :password, "Password", class: 'form-label' %>
  <%= f.password_field :password, class: 'form-text-box' %>
  <%= errors_for @user, :password %>
  
  <%= f.label :password_confirmation, "Confirm Password", class: 'form-label' %>
  <%= f.password_field :password_confirmation, class: 'form-text-box' %>
  <%= errors_for @user, :password_confirmation %>

  <%= f.submit "Create User", class: 'form-submit-box' %>
<% end %>
    <p>or</p>
    <div class="google">
      <%= link_to do %>
      <%= image_tag("google-icon.png") %>
      Sign in with Google
      <% end %>
    </div>
    <br>
  <br><%= link_to "Already have an account?", '/login' %>
</div>

app/views/users/show.html.erb
<div class="profile-page">
  <h1><%= @user.username %>'s Profile</h1>

<div class="user-info">
  <%= image_tag avatar_url(@user) %>
  <h4><%= @user.bio %></h4>
  <% if @user.favorite_genre != nil %>
  <h4>Favorite Genre - <%= @user.favorite_genre %></h4>
  <% end %>
</div>

<% if logged_in? && @user.id == current_user.id %>
  <%= link_to 'Edit Profile', edit_user_path(@user), :class => 'edit-profile' %>
<% end %>

</div>

app/views/worlds/_form.html.erb
<div class="create-world">
<h1>Create a New World</h1>
<%= form_for @world do |f| %>
  <%= f.label :title, class: 'form-label' %>
  <%= f.text_field :title, class: 'form-text-box'  %>
  <%= errors_for @world, :title %>

  <%= f.label :genre, class: 'form-label' %>
  <%= f.text_field :genre, class: 'form-text-box'  %>
  <%= errors_for @world, :genre %>

  <%= f.label :description, class: 'form-label' %>
  <%= f.text_area :description, class: 'form-text-area'  %>
  <%= errors_for @world, :description %>

  <%= f.label :inspiration, class: 'form-label'  %>
  <%= f.text_area :inspiration, class: 'form-text-area'  %>
  <%= errors_for @world, :inspiration %>

  <%= f.submit "Create World", class: 'form-submit-box' %>
<% end %>
</div>

app/views/worlds/index.html.erb
<div class="series-content">
  <% if logged_in? %>
    <h1><%= link_to "Create World", new_world_path %></h1>
  <% else %>
    <h1><%= link_to "Create World", '/login' %></h1>
  <% end %>
  <h2>Characters</h2>
  <h2>Culture</h2>
  <h2>Geography</h2>
  <h2>History</h2>
  <h2>Narrative</h2>
</div>

app/views/worlds/new.html.erb
<%= render 'form' %>